CREATE DATABASE IF NOT EXISTS dipti_portal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dipti_portal;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'admin'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS student_submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  institute VARCHAR(120) NOT NULL,
  batch VARCHAR(120) NOT NULL,
  course_name VARCHAR(120) NOT NULL,
  module VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  institute VARCHAR(120) NOT NULL,
  batch VARCHAR(120) NOT NULL,
  course_name VARCHAR(120) NOT NULL,
  module VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  profile_image_path VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (email)
) ENGINE=InnoDB;
